[project]
name = 'Flight-Delay-Insurance-System'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.flight-data-oracle]
path = 'contracts/flight-data-oracle.clar'
clarity_version = 3
epoch = '3.2'

[contracts.weather-correlation-engine]
path = 'contracts/weather-correlation-engine.clar'
clarity_version = 3
epoch = '3.2'

[contracts.instant-payout-system]
path = 'contracts/instant-payout-system.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
